### ISSUE TITLE
Two separate routes on one page

### ISSUE THREAD

**Issue by brandonfujii** [jlebensold/peckish#2]
With your approach of having routes as an array in the `navigationState` reducer, how would you navigate to two different routes on the same page. 
For example, let's say that I have two different `TouchableHighlight`s, with the first navigating forward to Page 1 and the second navigating forward to Page 2.

**Comment by jlebensold** [comment]
@brandonfujii in that case they would be two separate routes with two different indexes to two different pages. You could also encapsulate portions of functionality into higher order React Components. For example, `PageOne` and `PageTwo` both rely on `HeaderComponent`
