### ISSUE TITLE
Element type is invalid (When adding ApplicationTabs)

### ISSUE THREAD

**Issue by AkabaneK** [jlebensold/peckish#5]
I am getting the error that was initially shown in your tutorial video here :

https://youtu.be/6zVGVHWklg8?t=6m1s

I have named the file correctly "/app/containers/ApplicationTabs/index.ios.js" and the file contents are exactly as shown in the tutorial. However where the app worked in your video once you connected ApplicationTabs I am still getting that error after doing so myself. 

I am using a newer version of a lot of the react/react-native/redux modules however. 

I am not sure if the convention of exporting with files named with "index.ios.js" has changed or anything? Any help you could provide would be greatly appreciated.

Below is my package.json dependencies :
`
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-thunk": "^2.2.0"
  }
`

And this is my /app/containers/ApplicationTabs/index.ios.js file contents :
`
import { View, TabBarIOS, TabBarItemIOS } from 'react-native';
import React, { Component } from 'react';
import { connect } from 'react-redux';
class ApplicationTabs extends Component {
    render() {
        return (
            <View />
        );
    }
}
function mapStateToProps(state) {
    return {
    };
}
export default connect(mapStateToProps)(ApplicationTabs);
`

And the contents of AppContainer : 
`
import React, {Component} from 'react';
import {connect} from 'react-redux';
import {ActionCreators} from '../actions';
import {bindActionCreators} from 'redux';
import ApplicationTabs from './ApplicationTabs';
class AppContainer extends Component {
    render() {
        return (
            <ApplicationTabs { ...this.props } />
        )
    }
}
function mapDispatchToProps(dispatch) {
    return bindActionCreators(ActionCreators, dispatch);
}
export default connect( () => { return {} }, mapDispatchToProps)(AppContainer);
`

**Comment by jlebensold** [comment]
Hi @AkabaneK I'm afraid that React Native has changed their navigation quite a bit since I published this. I think it's been pulled out here: https://reactnavigation.org/

Hope that helps!
